apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: uo46o3xl7-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-8537361d53.et7h.p3.openshiftapps.com/rhtap/rhtap-qe:0e3f77cdd5aef118719fd5393eaca63ae8a3c770@sha256:44aac05ee08d8a86bedfa618b7aabd6c99bdee9f67db908abcda0042536c6f42
        name: container-image  
